# Generated by Django 3.1.4 on 2021-07-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='price',
            new_name='age',
        ),
    ]
